# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
a1=np.random.randint(1,5,100)
a2=np.random.randint(1,4,100)
a3=np.random.randint(10000,30001,100)

In [3]:
a1

array([3, 2, 4, 2, 3, 1, 1, 1, 1, 1, 1, 2, 3, 2, 3, 2, 4, 4, 4, 4, 1, 4,
       3, 3, 4, 1, 3, 3, 2, 3, 3, 3, 4, 4, 1, 1, 4, 3, 4, 3, 1, 1, 2, 1,
       2, 3, 2, 3, 2, 4, 4, 3, 1, 3, 1, 1, 3, 1, 3, 1, 1, 3, 2, 3, 3, 4,
       4, 3, 4, 1, 4, 2, 1, 2, 1, 3, 4, 4, 3, 3, 3, 3, 4, 4, 2, 1, 2, 1,
       4, 4, 1, 2, 3, 4, 4, 1, 2, 3, 3, 1])

In [4]:
a2

array([3, 1, 2, 2, 1, 3, 2, 2, 1, 3, 3, 3, 1, 2, 3, 2, 2, 3, 1, 2, 1, 3,
       2, 2, 1, 2, 3, 1, 2, 1, 1, 3, 3, 3, 3, 2, 3, 3, 3, 2, 2, 2, 1, 1,
       1, 2, 3, 3, 3, 1, 2, 3, 2, 1, 1, 3, 3, 2, 3, 1, 1, 3, 3, 3, 1, 1,
       1, 1, 2, 3, 1, 2, 1, 3, 2, 1, 3, 2, 2, 2, 1, 1, 3, 3, 2, 3, 1, 2,
       1, 1, 2, 3, 1, 1, 2, 1, 2, 1, 1, 3])

In [5]:
a3

array([28274, 27219, 21020, 24361, 25052, 23766, 24665, 15401, 11549,
       22862, 11465, 26016, 13293, 23850, 25801, 28629, 25027, 26026,
       14943, 21982, 24161, 22631, 10707, 28332, 21006, 14628, 27042,
       12990, 18097, 14325, 16750, 24890, 14867, 17022, 15172, 25077,
       29421, 19150, 12461, 10155, 27364, 28774, 29566, 13906, 23519,
       27183, 13936, 24284, 25388, 17887, 12380, 10632, 20447, 12520,
       22981, 15183, 26150, 26489, 18307, 29748, 13484, 13943, 23711,
       17087, 20203, 22014, 25162, 17414, 19002, 28225, 17450, 27606,
       14472, 15709, 16289, 23286, 20225, 20213, 15960, 23523, 14523,
       22723, 13332, 23287, 19726, 22050, 23029, 16837, 12813, 11196,
       27411, 22460, 25785, 17169, 22371, 22625, 22441, 16515, 22224,
       19692])

### Step 3. Let's create a DataFrame by joinning the Series by column

In [10]:
df=pd.DataFrame([a1,a2,a3]).T

In [11]:
df

0  1      2
0   3  3  28274
1   2  1  27219
2   4  2  21020
3   2  2  24361
4   3  1  25052
.. .. ..    ...
95  1  1  22625
96  2  2  22441
97  3  1  16515
98  3  1  22224
99  1  3  19692

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [9]:
col=['bedrs', 'bathrs', 'price_sqr_meter']


In [13]:
df.columns=col

In [14]:
df

bedrs  bathrs  price_sqr_meter
0       3       3            28274
1       2       1            27219
2       4       2            21020
3       2       2            24361
4       3       1            25052
..    ...     ...              ...
95      1       1            22625
96      2       2            22441
97      3       1            16515
98      3       1            22224
99      1       3            19692

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [43]:
df1=pd.DataFrame([a1]).T
df2=pd.DataFrame([a2]).T
df3=pd.DataFrame([a3]).T

In [47]:
con_df=pd.concat([df1,df2,df3])

In [48]:
con_df

0
0       3
1       2
2       4
3       2
4       3
..    ...
95  22625
96  22441
97  16515
98  22224
99  19692

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [50]:
con_df.shape[0]

300

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [54]:
con_df.reset_index(drop=True,inplace=True)

In [55]:
con_df

0
0        3
1        2
2        4
3        2
4        3
..     ...
295  22625
296  22441
297  16515
298  22224
299  19692

[300 rows x 1 columns]