## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [1]:
import numpy as np

In [2]:
#Intializing array
arr=np.arange(50,101)

In [231]:
#array with values ranging from 50 to 100
arr

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [6]:
#3x3 ones matrix
arr_1=np.ones((3,3))

In [13]:
#pad an array
arr_2=np.pad(arr_1,pad_width=1)

In [14]:
#Results
print("Original array:\n",arr_1)
print("Result array:\n",arr_2)

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Result array:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Convert a list and tuple into arrays

In [16]:
#creating list
lst=list(range(1,9))
#Converting list into an array
arr_3=np.array(lst)
arr_3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
#Creating tuple
tuple_=tuple(range(1,7))
#Converting tuple into an array
arr_4=np.array(tuple_).reshape(2,3)

In [19]:
arr_4

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#Creating an array from list using asarray method 
np.asarray(lst)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [232]:
#Creating an array from tuple using asarray method
np.asarray(tuple_).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [27]:
#Intializing Fahrenheit degrees
arr_5=np.array([0,12,45.21,34,99.91])

In [233]:
lst=[]
for i in arr_5:
    #Converting fahrenheit to celsius
    temp=(i-32)*(5/9)
    lst.append(temp)
print('Values in Fahrenheit Degrees',arr_5)
print('Values in Centigrade Degrees',np.asarray(lst))

Values in Fahrenheit Degrees [ 0.   12.   45.21 34.   99.91]
Values in Centigrade Degrees [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [234]:
arr_6=np.array(['0']*3,dtype='int')

In [47]:
#Importing sys to find bytes value
import sys

In [240]:
print('Size of an array:',arr_6.size)
print("Length of one array element in bytes:",sys.getsizeof(arr_6[0]))
print("Total bytes consumed by the elements of the array:",sys.getsizeof(arr_6))

Size of an array: 3
Length of one array element in bytes: 32
Total bytes consumed by the elements of the array: 120


Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Exercise 6: Get the unique elements of an array

In [87]:
#Creating an array
lst_arr=np.array([10,10,20,20,30,30])
lst_arr2=np.array([[1,1],[2,3]])

In [245]:
print("Original array",lst_arr)
#Using unique method to get unique elements
print("Unique Elements of the above array:\n",np.unique(lst_arr))
print("Original array:\n",lst_arr2)
print("Unique elements of the above array:\n",np.unique(lst_arr2))



Original array [10 10 20 20 30 30]
Unique Elements of the above array:
 [10 20 30]
Original array:
 [[1 1]
 [2 3]]
Unique elements of the above array:
 [1 2 3]


Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


## Exercise 7: Change the dimension of an array


In [93]:
#Original array with shape (10,) 
ori_arr=np.array(range(1,10))

In [247]:
print("Original array:",ori_arr)
print("Result array:\n",ori_arr.reshape(3,3))

Original array: [1 2 3 4 5 6 7 8 9]
Result array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [96]:
#Creatin 1-D array of 30 evenly spaced elements between 2.5 and 6.5 inclusive using linspace method
np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [97]:
#Creating 1-D arrays
array1=np.array([10,20,30])
array2=np.array([40,50,60])

In [255]:
#Converting 1-D arrays as columns into 2-D array
print("Array1:",array1)
print("Array2:",array2)
print("Converted array:\n",np.stack((array1,array2),axis=1))

Array1: [10 20 30]
Array2: [40 50 60]
Converted array:
 [[10 40]
 [20 50]
 [30 60]]


Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [257]:
#Creating 5x5 zero matrix 
zero_arr=np.zeros((5,5))
mul_lst=list(range(0,5))

In [260]:
print('Original matrix:\n',zero_arr)
print("Row values ranging from 0 to 4\n",zero_arr+mul_lst)

Original matrix:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [330]:
multi_list=[]
for i in range(1,100):
    #Getting all values which are divisible either by 3 or 5
    if (i%3==0 or i%5==0):
        multi_list.append(i)
print("Numbers which are divisible by 3 or 5:\n",np.asarray(multi_list)) 
print("Sum of numbers:\n",np.sum(np.asarray(multi_list)))

Numbers which are divisible by 3 or 5:
 [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
Sum of numbers:
 2318


[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [268]:
x=np.arange(4)
y=np.arange(8).reshape(2,4)

In [271]:
print("One dimensional array:",x)
print("Two dimensional array:\n",y)
#Combinig a one and two dimensional array together and display their elements
for i,j in np.nditer([x,y]):
    print(f'{i}:{j}')

One dimensional array: [0 1 2 3]
Two dimensional array:
 [[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [285]:
array=np.array([[0.42436315,0.48558583,0.32924763]
         ,[0.7439979,0.58220701,0.38213418]
         ,[0.5097581,0.34528799,0.1563123 ]])

In [331]:
print("Original Array:\n",array)
#Replacing elements which are greater than 0.5
array[array>0.5]=0.5
print("Replacing all elements greater than 0.5 with 0.5:\n",array)


Original Array:
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]
Replacing all elements greater than 0.5 with 0.5:
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

In [303]:
#Intializing empty array
emp_arr=np.array([])

In [308]:
#using concatenate method to add one row
emp_arrr=np.concatenate((emp_arr,[10,20,30]))

In [305]:
emp_arrr

array([10., 20., 30.])

In [309]:
#Using stack method to add a row 
b=np.arange(40,70,10)
c=np.stack((emp_arrr,b),axis=0)

array([[10., 20., 30.],
       [40., 50., 60.]])

In [311]:
print('Empty array',emp_arr)
print('After adding two arrays:\n',c)

Empty array []
After adding two arrays:
 [[10 20 30]
 [40 50 60]]


Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [217]:
#Intializing array
a_arr=np.arange(1,4)
b_arr=np.arange(2,5)

In [318]:
print("Original arrays:\n",a_arr,'\n',b_arr)
#Joining array along the axis
print("Sequence of array along new axis:\n",np.stack((a_arr,b_arr)))

Original arrays:
 [1 2 3] 
 [2 3 4]
Sequence of array along new axis:
 [[1 2 3]
 [2 3 4]]


In [223]:
#Intializing array
c_arr=a_arr.reshape((3,1))
d_arr=b_arr.reshape((3,1))

In [329]:
print("Original Array:\n",c_arr,'\n \n',d_arr)
#Joining array 
print("Sequence of arrays along a new axis:\n",np.stack((c_arr,d_arr)).reshape(6,1))

Original Array:
 [[1]
 [2]
 [3]] 
 
 [[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
