##  How to replace items that satisfy a condition with another value in numpy array?

### Q. Replace all odd numbers in arr with -1



In [1]:
import numpy as np

In [2]:
#Declaring array of range 0 to 10
arr=np.arange(10)

In [3]:
#Replacing odd numbers by -1
arr[arr%2!=0]=-1

In [4]:
#Array in which odd numbers are replaced by -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## How to replace items that satisfy a condition without affecting the original array?

### Q. Replace all odd numbers in arr with -1 without changing arr

In [5]:
arr1=np.arange(10)

In [34]:
#Replacing odd numbers by -1 using where function
out=np.where(arr1%2!=0,-1,arr)

In [36]:
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## How to reshape an array?

### Q. Convert a 1D array to a 2D array with 2 rows



In [38]:
#Converting a 1D array to a 2D array
np.arange(10).reshape((-1,2))#Setting -1 automatically defines required column

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### Q. Stack the arrays a and b horizontally.



In [39]:
#Intializing array
a= np.arange(10).reshape((2,-1))
b=np.repeat(2,10).reshape((2,-1))

In [41]:
#Horizontal Stack
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 2, 2, 2, 2, 2],
       [5, 6, 7, 8, 9, 2, 2, 2, 2, 2]])

In [46]:

np.c_[a,b]

array([[0, 1, 2, 3, 4, 2, 2, 2, 2, 2],
       [5, 6, 7, 8, 9, 2, 2, 2, 2, 2]])

In [49]:
#Joining two arrays horizontally
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 4, 2, 2, 2, 2, 2],
       [5, 6, 7, 8, 9, 2, 2, 2, 2, 2]])

### Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.



In [50]:
#Creating an array
a=np.array([1,2,3])

In [54]:
#Creating an array by repeating same array itself
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [59]:
#Creating an array by R class 
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Q. Get the common items between a and b



In [61]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [62]:
#Getting common items between a and b
np.intersect1d(a,b)

array([2, 4])

### Q. From array a remove all items present in array b



In [47]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [64]:
#Removing all items present in array b
np.setdiff1d(a,b)

array([1, 3, 5, 6])

### Q. Get the positions where elements of a and b match



In [66]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [67]:
#Getting the position where elements of a and b match
np.where(a==b)

(array([1, 3, 5, 7]),)

### Q. Get all items between 5 and 10 from a.



In [69]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [70]:
a[np.where((a>5) & (a<=10))]

array([ 6,  9, 10])

In [75]:
a[(a>5) & ((a<=10))]

array([ 6,  9, 10])

In [77]:
a[np.logical_and(a>=5,a<=10)]

array([ 6,  9, 10])

### Q. Convert the function maxx that works on two scalars, to work on two arrays.



In [77]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1,])

In [78]:
np.maximum(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [79]:
def pair_max(a,b):
    return (np.maximum(a,b))
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [80]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
maxx(2,3)

3

In [83]:
pair=np.vectorize(maxx,otypes=[int])

In [84]:
pair(a,b)

array([6, 7, 9, 8, 9, 7, 5])

### Q. Swap columns 1 and 2 in the array arr.



In [86]:
arr = np.arange(9).reshape(3,3)

In [91]:
#Interchaning two axis of an array
np.swapaxes(arr,0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

### Q. Reverse the columns of a 2D array arr.



In [106]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
#Reversing the columns of an array
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.



In [101]:
#Creating a 2D array of shape 5x3
np.random.random((5,3))

array([[0.40167419, 0.59322127, 0.30724022],
       [0.71215312, 0.7673366 , 0.40207619],
       [0.23690419, 0.71603175, 0.89603648],
       [0.76380146, 0.91229474, 0.69537443],
       [0.00851284, 0.22675092, 0.63120643]])

In [104]:
np.random.uniform(5,10,(5,3))

array([[8.85660322, 5.10375975, 8.16824117],
       [8.74401941, 7.49253506, 6.12398323],
       [5.99031432, 8.80265356, 5.84555418],
       [5.44169907, 8.42679909, 9.76696673],
       [5.01974133, 7.56096132, 9.06310481]])

### Q. Print or show only 3 decimal places of the numpy array rand_arr.



In [118]:
rand_arr = np.random.random((5,3))

In [121]:
rand_arr

array([[0.75464769, 0.29596171, 0.88393648],
       [0.32551164, 0.1650159 , 0.39252924],
       [0.09346037, 0.82110566, 0.15115202],
       [0.38411445, 0.94426071, 0.98762547],
       [0.45630455, 0.82612284, 0.25137413]])

In [124]:
#Setting decimal places to 3
np.set_printoptions(precision=3)

In [125]:
rand_arr

array([[0.755, 0.296, 0.884],
       [0.326, 0.165, 0.393],
       [0.093, 0.821, 0.151],
       [0.384, 0.944, 0.988],
       [0.456, 0.826, 0.251]])

### Q. Pretty print rand_arr by suppressing the scientific notation (like 1e10)



In [126]:
np.random.seed(100)
rand_arr = np.random.random((5,3))/1e3

In [127]:
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04],
       [5.751e-04, 8.913e-04, 2.092e-04],
       [1.853e-04, 1.084e-04, 2.197e-04]])

In [130]:
#Suppressing the scientific notation 
np.set_printoptions(suppress=True,precision=6)

In [133]:
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137],
       [0.000575, 0.000891, 0.000209],
       [0.000185, 0.000108, 0.00022 ]])

### Q. Limit the number of items printed in python numpy array a to a maximum of 6 elements.



In [134]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [135]:
#Setting the number of elements to be printed
np.set_printoptions(threshold=6)

In [136]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

### Q. Find the mean, median, standard deviation of iris's sepallength (1st column)



In [141]:
from sklearn.datasets import load_iris

In [142]:
iris=load_iris()

In [143]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [154]:
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#Getting the iris data from the url
iris1=np.genfromtxt(url,delimiter=',',dtype=object)

In [155]:
iris1[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

In [146]:
iris1[:,4][:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype=object)

In [156]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [21]:
sepallength.mean()

5.843333333333334

In [22]:
sepallength.std()

0.8253012917851409

In [24]:
np.median(sepallength)

5.8

In [157]:
val,count=np.unique(iris1[:,2],return_counts=True)

In [158]:
val[np.argmax(count)]

b'1.5'

In [159]:
np.set_printoptions(suppress=True)

### Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.



In [165]:
#Finding the position of a value greater than 1.0
np.argwhere(iris1[:,3].astype(float)>1.0)[0]

array([50])

### Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.



In [169]:

import numpy as np
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [170]:
#Replacing all values greater than 30 to 30
a[a>30]=30

In [171]:
#Replacing all values greater than 10 to 10
a[a<10]=10

In [172]:
print(a)

[27.626842 14.6401   21.801362 30.       10.       10.       30.
 30.       10.       29.179573 30.       11.250904 10.081083 10.
 11.765177 30.       30.       10.       30.       14.429614]


In [173]:
#Replacing all values greater than 30 to 30 and less than 10 to 10 using clip
np.clip(a,a_max=30,a_min=10)

array([27.626842, 14.6401  , 21.801362, 30.      , 10.      , 10.      ,
       30.      , 30.      , 10.      , 29.179573, 30.      , 11.250904,
       10.081083, 10.      , 11.765177, 30.      , 30.      , 10.      ,
       30.      , 14.429614])

In [174]:
#Replacing all values greater than 30 to 30 and less than 10 to 10 using where
np.where(a<10,10,np.where(a>30,30,a))

array([27.626842, 14.6401  , 21.801362, 30.      , 10.      , 10.      ,
       30.      , 30.      , 10.      , 29.179573, 30.      , 11.250904,
       10.081083, 10.      , 11.765177, 30.      , 30.      , 10.      ,
       30.      , 14.429614])

### Q. Get the positions of top 5 maximum values in a given array a.



In [175]:
#Getting the posotions o top 5 maximum values in a given array
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [181]:
a.argsort()[-5:]

array([18,  7,  3, 10, 15])

In [194]:
np.partition(a,kth=-6)[-5:]

array([40.995013, 41.466785, 42.39403 , 44.674776, 48.952565])

In [178]:
np.argpartition(a,kth=-5)[-5:]

array([18,  7,  3, 10, 15])

### Q. Convert array_of_arrays into a flat linear 1d array.



In [195]:
arr1=np.arange(0,3)
arr2=np.arange(3,7)
arr3=np.arange(7,10)
arr4=np.arange(10,13)

In [196]:
array_of_array=np.array([arr1,arr2,arr3,arr4],dtype=object)

In [59]:
np.concatenate(array_of_array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
#Creating a 1-d flat array using list comprehension
arr_2d=[a for arr in array_of_array for a in arr]

In [199]:
arr_2d

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

### Q. Create a rank array of the same shape as a given numeric array a.



In [200]:

np.random.seed(100)
a=np.random.randint(20,size=(2,5))

In [121]:
a.ravel().argsort().argsort().reshape(a.shape)

array([[5, 3, 4, 8, 9],
       [6, 0, 1, 2, 7]])

### Q. Compute the min-by-max for each row for given 2d numpy array.



In [211]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a


array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [212]:
np.apply_along_axis(lambda x: np.min(x)/np.max(x), axis=1, arr=a)

array([0.444444, 0.125   , 0.5     , 1.      , 0.111111])

### Q. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.




In [221]:
#Creating an array
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

Array:  [0 0 3 0 2 4 2 2 2 2]


In [214]:
#Intializing an array value True
out=np.full(a.shape,fill_value=True)

In [222]:
#Getting the position of unique values
unique_position=np.unique(a,return_index=True)[1]

In [224]:
unique_position

array([0, 4, 2, 5])

In [227]:
#Changing the unique value position to False
out[unique_position]=False

In [228]:
out

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

### Q. Drop all nan values from a 1D numpy array



In [148]:
b=np.array([1,2,3,np.nan,5,6,7,np.nan])

In [234]:
#Dropping all nan values
b[~np.isnan(b)]

array([6, 3, 4, 8, 9, 7, 1])